
DATASETS = ["CrypticBio-Common"]
SEED = 42


rule all:
	input:
		expand("input/{dataset}_country.tsv",
			dataset=DATASETS
		),
		expand("input/{dataset}_continent.tsv",
			dataset=DATASETS
		)

rule country2continent:
	input:
		"input/{dataset}_country.tsv"
	output:
		"input/{dataset}_continent.tsv"
	shell:
		"""
		python3 scripts/country2continent.py --input-file {input} --output-file {output}
		"""

rule lonlat2country:
	input:
		"input/{dataset}.csv"
	output:
		"temp/{dataset}_country.tsv"
	shell:
		"""
		julia scripts/lon-lat2country.jl --input-file {input} --output-file {output}
		"""
